MoveDescriptions::
	dw PoundDescription
	dw KarateChopDescription
	dw DoubleslapDescription
	dw CometPunchDescription
	dw MegaPunchDescription
	dw PayDayDescription
	dw FirePunchDescription
	dw IcePunchDescription
	dw ThunderpunchDescription
	dw ScratchDescription
	dw VicegripDescription
	dw GuillotineDescription
	dw RazorWindDescription
	dw SwordsDanceDescription
	dw CutDescription
	dw GustDescription
	dw WingAttackDescription
	dw WhirlwindDescription
	dw FlyDescription
	dw BindDescription
	dw SlamDescription
	dw VineWhipDescription
	dw StompDescription
	dw DoubleKickDescription
	dw MegaKickDescription
	dw JumpKickDescription
	dw RollingKickDescription
	dw SandAttackDescription
	dw HeadbuttDescription
	dw HornAttackDescription
	dw FuryAttackDescription
	dw HornDrillDescription
	dw TackleDescription
	dw BodySlamDescription
	dw WrapDescription
	dw TakeDownDescription
	dw ThrashDescription
	dw DoubleEdgeDescription
	dw TailWhipDescription
	dw PoisonStingDescription
	dw TwineedleDescription
	dw PinMissileDescription
	dw LeerDescription
	dw BiteDescription
	dw GrowlDescription
	dw RoarDescription
	dw SingDescription
	dw SupersonicDescription
	dw SonicboomDescription
	dw DisableDescription
	dw AcidDescription
	dw EmberDescription
	dw FlamethrowerDescription
	dw MistDescription
	dw WaterGunDescription
	dw HydroPumpDescription
	dw SurfDescription
	dw IceBeamDescription
	dw BlizzardDescription
	dw PsybeamDescription
	dw BubblebeamDescription
	dw AuroraBeamDescription
	dw HyperBeamDescription
	dw PeckDescription
	dw DrillPeckDescription
	dw SubmissionDescription
	dw LowKickDescription
	dw CounterDescription
	dw SeismicTossDescription
	dw StrengthDescription
	dw AbsorbDescription
	dw MegaDrainDescription
	dw LeechSeedDescription
	dw GrowthDescription
	dw RazorLeafDescription
	dw SolarbeamDescription
	dw PoisonpowderDescription
	dw StunSporeDescription
	dw SleepPowderDescription
	dw PetalDanceDescription
	dw StringShotDescription
	dw DragonRageDescription
	dw FireSpinDescription
	dw ThundershockDescription
	dw ThunderboltDescription
	dw ThunderWaveDescription
	dw ThunderDescription
	dw RockThrowDescription
	dw EarthquakeDescription
	dw FissureDescription
	dw DigDescription
	dw ToxicDescription
	dw ConfusionDescription
	dw PsychicMDescription
	dw HypnosisDescription
	dw MeditateDescription
	dw AgilityDescription
	dw QuickAttackDescription
	dw RageDescription
	dw TeleportDescription
	dw NightShadeDescription
	dw MimicDescription
	dw ScreechDescription
	dw DoubleTeamDescription
	dw RecoverDescription
	dw HardenDescription
	dw MinimizeDescription
	dw SmokescreenDescription
	dw ConfuseRayDescription
	dw WithdrawDescription
	dw DefenseCurlDescription
	dw BarrierDescription
	dw LightScreenDescription
	dw HazeDescription
	dw ReflectDescription
	dw FocusEnergyDescription
	dw BideDescription
	dw MetronomeDescription
	dw MirrorMoveDescription
	dw SelfdestructDescription
	dw EggBombDescription
	dw LickDescription
	dw SmogDescription
	dw SludgeDescription
	dw BoneClubDescription
	dw FireBlastDescription
	dw WaterfallDescription
	dw ClampDescription
	dw SwiftDescription
	dw SkullBashDescription
	dw SpikeCannonDescription
	dw ConstrictDescription
	dw AmnesiaDescription
	dw KinesisDescription
	dw SoftboiledDescription
	dw HiJumpKickDescription
	dw GlareDescription
	dw DreamEaterDescription
	dw PoisonGasDescription
	dw BarrageDescription
	dw LeechLifeDescription
	dw LovelyKissDescription
	dw SkyAttackDescription
	dw TransformDescription
	dw BubbleDescription
	dw DizzyPunchDescription
	dw SporeDescription
	dw FlashDescription
	dw PsywaveDescription
	dw SplashDescription
	dw AcidArmorDescription
	dw CrabhammerDescription
	dw ExplosionDescription
	dw FurySwipesDescription
	dw BonemerangDescription
	dw RestDescription
	dw RockSlideDescription
	dw HyperFangDescription
	dw SharpenDescription
	dw ConversionDescription
	dw TriAttackDescription
	dw SuperFangDescription
	dw SlashDescription
	dw SubstituteDescription
	dw StruggleDescription
	dw SketchDescription
	dw TripleKickDescription
	dw ThiefDescription
	dw SpiderWebDescription
	dw MindReaderDescription
	dw NightmareDescription
	dw FlameWheelDescription
	dw SnoreDescription
	dw NailDownDescription
	dw FlailDescription
	dw Conversion2Description
	dw CoinHurlDescription
	dw CottonSporeDescription
	dw ReversalDescription
	dw SpiteDescription
	dw PowderSnowDescription
	dw ProtectDescription
	dw MachPunchDescription
	dw ScaryFaceDescription
	dw FaintAttackDescription
	dw SweetKissDescription
	dw BellyDrumDescription
	dw SludgeBombDescription
	dw MudSlapDescription
	dw OctazookaDescription
	dw SpikesDescription
	dw ZapCannonDescription
	dw ForesightDescription
	dw DestinyBondDescription
	dw PerishSongDescription
	dw SynchronizeDescription
	dw DetectDescription
	dw BoneLockDescription
	dw LockOnDescription
	dw OutrageDescription
	dw SandstormDescription
	dw GigaDrainDescription
	dw EndureDescription
	dw CharmDescription
	dw RolloutDescription
	dw FalseSwipeDescription
	dw SwaggerDescription
	dw MilkDrinkDescription
	dw SparkDescription
	dw FuryCutterDescription
	dw SteelWingDescription
	dw StalkerDescription
	dw AttractDescription
	dw SleepTalkDescription
	dw BellChimeDescription
	dw ReturnDescription
	dw PresentDescription
	dw FrustrationDescription
	dw SafeguardDescription
	dw PainSplitDescription
	dw SacredFireDescription
	dw MagnitudeDescription
	dw DynamicpunchDescription
	dw MegaphoneDescription
	dw DragonbreathDescription
	dw BatonPassDescription
	dw EncoreDescription
	dw PursuitDescription
	dw RapidSpinDescription
	dw TemptDescription
	dw IronTailDescription
	dw RockHeadDescription
	dw VitalThrowDescription
	dw MorningSunDescription
	dw SynthesisDescription
	dw MoonlightDescription
	dw HiddenPowerDescription
	dw CrossCutterDescription
	dw TwisterDescription
	dw RainDanceDescription
	dw SunnyDayDescription
	dw F2Description
	dw F3Description
	dw F4Description
	dw UprootDescription
	dw WindRideDescription
	dw WaterSportDescription
	dw StrongArmDescription
	dw BrightMossDescription
	dw WhirlpoolDescription
	dw BounceDescription

PoundDescription:
	db   "äs し←ぽüどを Üws"
	next "äxを はÄsä こtげx@"

KarateChopDescription:
	db   "Qpmプで äxを こtげx"
	next "HりSqFg(mTが でsすs@"

DoubleslapDescription:
	db   "äxを vtふyビlPで"
	next "2-5ws れんぞyで こtげx@"

CometPunchDescription:
	db   "äxを れんぞyで üぐりÜz"
	next "2-5ws れんぞyで こtげx@"

MegaPunchDescription:
	db   "rのすごs ÖwらをこmÄ パlQで"
	next "äxを üぐ←ä こtげx@"

PayDayDescription:
	db   "こばんをüげä äxを こtげx"
	next "せんötごに vwねが äにはsる@"

FirePunchDescription:
	db   "ほのvをこmÄ パlQで こtげx"
	next "äxを szどさせるこöがrる@"

IcePunchDescription:
	db   "れsxをこmÄ パlQで こtげx"
	next "äxを こvらせるこöがrる@"

ThunderpunchDescription:
	db   "でんげxをこmÄ パlQで こtげx"
	next "äxを ;(させるこöがrる@"

ScratchDescription:
	db   "するどsRaを Üws"
	next "äxを ひ←wsä こtげx@"

VicegripDescription:
	db   "vvxüZK[を Üws"
	next "äxを はさんで こtげx@"

GuillotineDescription:
	db   "vvxüZK[を Üw←ä"
	next "äxを はさd せんötふのtにする@"

RazorWindDescription:
	db   "1P-lmで wぜのssばを Üyり"
	next "ÜぎのP-lで äxを こtげx@"

SwordsDanceDescription:
	db   "ÄÄwsの vどりを vど←ä"
	next "こtげxを グ-lörげる@"

CutDescription:
	db   "するどsF;s Raüどを Üw←ä"
	next "äxを xりÜzä こtげx@"

GustDescription:
	db   "Üばさで Üvswぜを vこし"
	next "それを äxにぶÜzä こtげx@"

WingAttackDescription:
	db   "Üばさを vvxy ひろげä"
	next "そのまま äxに ÄsrÄりする@"

WhirlwindDescription:
	db   "Üvswぜで äxを ふxöばす"
	next "ふxöばすö せんötは vわる@"

FlyDescription:
	db   "1P-lmで そらに öびÄ←ä"
	next "ÜぎのP-lで äxを こtげx@"

BindDescription:
	db   "2-5P-lのrsだ üがswらだs"
	next "Üるを Üw←ä äxを しmÜzる@"

SlamDescription:
	db   "üがsLmポs Rgüどを"
	next "äxに ÄÄxÜzä こtげx@"

VineWhipDescription:
	db   "]Qのvtに ほそüがs Üるを "
	next "äxに ÄÄxÜzä こtげx@"

StompDescription:
	db   "vvxürしで ふdÜzä こtげx"
	next "äxを ひるませるこöがrる@"

DoubleKickDescription:
	db   "2ほんの rしをÜw←ä äxを"
	next "2ws れんぞyで こtげx@"

MegaKickDescription:
	db   "rのすごs ÖwらをこmÄ GmHで"
	next "äxを z←öばしä こtげx@"

JumpKickDescription:
	db   "ジnlプしÄ sxvsで GmHを"
	next "yりだす はずすö ダa-ジをtzる@"

RollingKickDescription:
	db   "wらだを すばsy 1wsäんさせ"
	next "そのsxvsで GmHを yりだす@"

SandAttackDescription:
	db   "äxの wvüどに すüをwzä "
	next "msÖ<PK>tりÜを さげさせる@"

HeadbuttDescription:
	db   "rÄまwら Ü←こんで こtげx"
	next "äxを ひるませるこöがrる@"

HornAttackDescription:
	db   "öが←Ä RYを Üws"
	next "äxを ÜÜsä こtげx@"

FuryAttackDescription:
	db   "öが←Ä RYを Üws"
	next "2-5ws れんぞyで こtげx@"

HornDrillDescription:
	db   "RYを ドりgのvtに wsäんさせ"
	next "äxを ÜÜx せんötふのtにする@"

TackleDescription:
	db   "wらだぜんÄsを Üw←ä"
	next "äxに ÄsrÄりしä こtげx@"

BodySlamDescription:
	db   "wらだごö Ävれこんで こtげx"
	next "äxを ;(させるこöがrる@"

WrapDescription:
	db   "2-5P-lのrsだ üがswらだs"
	next "RgをÜw←ä äxを しmÜzる@"

TakeDownDescription:
	db   "sxvsをÜzä äxに ÄsrÄり"
	next "じぶんrすこし ダa-ジをtzる@"

ThrashDescription:
	db   "2-3P-lのrsだ rばれÜづzる"
	next "rばれÄröは こんらんしäしまt@"

DoubleEdgeDescription:
	db   "sのÖをwzä äxに ÄsrÄり"
	next "じぶんrすこし ダa-ジをtzる@"

TailWhipDescription:
	db   "äxに し←ぽをふ←ä tだんさせä"
	next "ぼtぎ<MN>を さげさせる@"

PoisonStingDescription:
	db   "どyのrる Zりs RYで こtげx"
	next "äxに どyをrÄuるこöがrる@"

TwineedleDescription:
	db   "り<MN>täの Zりを Üw←ä"
	next "äxを 2ws れんぞyで こtげx@"

PinMissileDescription:
	db   "するどsZりを äxに は←ししä"
	next "2-5ws れんぞyで こtげx@"

LeerDescription:
	db   "äxを にらんで vびuさせä "
	next "ぼtぎ<MN>を さげさせる@"

BiteDescription:
	db   "するどs はで wdÜsä こtげx"
	next "äxを ひるませるこöがrる@"

GrowlDescription:
	db   "wわsyüsä äxを tだんさせä"
	next "こtげxを さげさせる@"

RoarDescription:
	db   "ほuä äxを にげださせる"
	next "äxが にげるö せんötは vわる@"

SingDescription:
	db   "ここÖvs tÄごuで"
	next "äxを ふwsねlりへö さそt@"

SupersonicDescription:
	db   "wらだwら wsvんぱを は←しä"
	next "äxを こんらんさせるこöがrる @"

SonicboomDescription:
	db   "し<MN>tげxはで äxを こtげx"
	next "20の xま←Äダa-ジを rÄuる@"

DisableDescription:
	db   "Ö<MN>tのtり<MN>yで äxの tごxを"
	next "ömä わざを 1Ü Üwuüyする@"

AcidDescription:
	db   "Üvsさんで äxの ひふを öwす"
	next "ぼtぎ<MN>を さげるこöがrる@"

EmberDescription:
	db   "Ösさü ほのvで こtげx"
	next "äxを szどさせるこöがrる@"

FlamethrowerDescription:
	db   "すごs ほのvで こtげx"
	next "äxを szどさせるこöがrる@"

MistDescription:
	db   "しろsxりで wらだを vvs"
	next "のtり<MN>yを さげられüsvtにする@"

WaterGunDescription:
	db   "dずを は←ししä"
	next "äxを こtげx@"

HydroPumpDescription:
	db   "dずを rのすごs sxvsで"
	next "は←ししä äxを こtげx@"

SurfDescription:
	db   "dずに üdを vこし それを"
	next "rのすごs Öwらで ÄÄxÜzる@"

IceBeamDescription:
	db   "れsxを は←ししä こtげx"
	next "äxを こvらせるこöがrる@"

BlizzardDescription:
	db   "txを Üvswぜにのせä こtげx"
	next "äxを こvらせるこöがrる@"

PsybeamDescription:
	db   "ふしぎü ひwりを は←しする"
	next "äxを こんらんさせるこöがrる@"

BubblebeamDescription:
	db   "dずを sxvsvy は←しする"
	next "äxの すばsさを さげるこöがrる@"

AuroraBeamDescription:
	db   "にじsろの ひwりを は←しする"
	next "こtげxを さげるこöがrる@"

HyperBeamDescription:
	db   "ダa-ジは vvxsが Üwtö"
	next "ÜぎのP-l tごzüyü←äしまt@"

PeckDescription:
	db   "üがs yÖばしを Üw←ä "
	next "äxを ÜÜsä こtげx@"

DrillPeckDescription:
	db   "yÖばしを Ö<PK>tしんに wらだを"
	next "wsäんさせä äxに ö←しんする@"

SubmissionDescription:
	db   "じぶんごö じmんに ÄÄxÜzる"
	next "じぶんにr すこしダa-ジ@"

LowKickDescription:
	db   "PB[lグvy rしを ひ←wzる"
	next "äxを ひるませるこöがrる@"

CounterDescription:
	db   "äxwらtzÄ ぶÜりこtげxの"
	next "ダa-ジを ばsにしäwuす@"

SeismicTossDescription:
	db   "sんり<MN>yを りvtしä üげる"
	next "hべgぶんの ダa-ジを rÄuる@"

StrengthDescription:
	db   "ぜんしんに すごsÖwらを Ämä"
	next "äxを こtげx@"

AbsorbDescription:
	db   "äxに rÄuÄ ダa-ジの"
	next "はんぶん Äsり<MN>yを wsふyする@"

MegaDrainDescription:
	db   "äxに rÄuÄ ダa-ジの"
	next "はんぶん Äsり<MN>yを wsふyする@"

LeechSeedDescription:
	db   "äxの wらだに PXをtuä"
	next "P-lごöに Äsり<MN>yを すsöる@"

GrowthDescription:
	db   "s←xに wらだを せsÖ<MN>tさせä"
	next "öyし<PK>こtげxを rげる@"

RazorLeafDescription:
	db   "は←ぱで äxを xりÜzる"
	next "HりSqFg(mTが でsすs@"

SolarbeamDescription:
	db   "1P-lmで ひwりを x<PK>tし<PK>t"
	next "ÜぎのP-lで äxを こtげx@"

PoisonpowderDescription:
	db   "どyそを ふyんだ こüを ふりまx"
	next "äxに どyをrÄuる@"

StunSporeDescription:
	db   "しびれる こüを ふりまx"
	next "äxを ;(させäしまt@"

SleepPowderDescription:
	db   "ねlyüる こüを ふりまx"
	next "äxを ねlらせäしまt@"

PetalDanceDescription:
	db   "2-3P-lのrsだ rばれÜづzる"
	next "rばれÄröは こんらんしäしまt@"

StringShotDescription:
	db   "söを äxの wらだに まxÜz"
	next "すばsさを さげさせる@"

DragonRageDescription:
	db   "し<MN>tげxはで äxを こtげx"
	next "40の xま←Äダa-ジを rÄuる@"

FireSpinDescription:
	db   "2-5P-lのrsだ äxを"
	next "ほのvの Ö<PK>tしんに öじこmる@"

ThundershockDescription:
	db   "でんげxを rびせä こtげx"
	next "äxを ;(させるこöがrる@"

ThunderboltDescription:
	db   "Üvsでんげxを rびせä こtげx"
	next "äxを ;(させるこöがrる@"

ThunderWaveDescription:
	db   "vわsでんげxを äxに ぶÜzä"
	next ";(させäしまt@"

ThunderDescription:
	db   "äxに lw←ä wdüりを vöす"
	next ";(させるこöがrる@"

RockThrowDescription:
	db   "Ösさü sわを üげÜzä"
	next "äxを こtげx@"

EarthquakeDescription:
	db   "じmんを tらしä こtげx"
	next "öんでる äxsがsに だsダa-ジ@"

FissureDescription:
	db   "じわれを vこしä äxを のdこl"
	next "のdこまれるö せんötふのtにüる@"

DigDescription:
	db   "1P-lmで じmんに rぐり"
	next "ÜぎのP-lで äxを こtげx@"

ToxicDescription:
	db   "じ<MN>じ<MN>に ダa-ジがふuる どyを"
	next "äxに rÄuる@"

ConfusionDescription:
	db   "Ö<MN>tのtり<MN>yで こtげx"
	next "äxを こんらんさせるこöがrる@"

PsychicMDescription:
	db   "Üvsねんりxで äxを こtげx"
	next "öyし<PK>ぼtぎ<MN>を さげるこöがrる@"

HypnosisDescription:
	db   "äxに rんじを wzä"
	next "ふws ねlりへö さそt@"

MeditateDescription:
	db   "eガのポ-ズで ねl←Ä Öwらを"
	next "ひxだし こtげxを rげる@"

AgilityDescription:
	db   "Öwらを ぬsä wらだを wるyし"
	next "すばsさを グ-lörげる@"

QuickAttackDescription:
	db   "rのすごs はsさで tごsä "
	next "wüらず せんせsこtげxする@"

RageDescription:
	db   "こtげxされるÄびに swりで"
	next "こtげxが rが←äsy@"

TeleportDescription:
	db   "Ö<MN>tのtり<MN>yを Üw←ä"
	next "せんötwら だ←し<PK>Üする@"

NightShadeDescription:
	db   "äxに vそろしs まぼろしを dせ"
	next "hべgぶんの ダa-ジを rÄuる@"

MimicDescription:
	db   "äxが Üw←Ä わざが "
	next "そのöxだz じぶんの わざにüる@"

ScreechDescription:
	db   "ssüvöを だしä äxの"
	next "ぼtぎ<MN>を ガHmöさげさせる@"

DoubleTeamDescription:
	db   "ぶんしんで äxを まどわせ"
	next "msÖ<PK>tりÜを さげさせる@"

RecoverDescription:
	db   "GズÜsÄ wらだを Äsり<MN>yの"
	next "はんぶんだz wsふyする@"

HardenDescription:
	db   "ぜんしんに Öwらをこm wÄyüり"
	next "ぼtぎ<MN>を rげる@"

MinimizeDescription:
	db   "wらだを Öぢmä Ösさyüり"
	next "äxの msÖ<PK>tりÜを さげさせる@"

SmokescreenDescription:
	db   "zlりs M[üどで äxの "
	next "msÖ<PK>tりÜを さげさせる@"

ConfuseRayDescription:
	db   "rsしsひwりで äxを まどわし"
	next "こんらんさせäしまt@"

WithdrawDescription:
	db   "wÄswらに rぐりこんで"
	next "ぼtぎ<MN>を rげる@"

DefenseCurlDescription:
	db   "wらだを まるmä x<PK>tし<MN>を"
	next "wyし ぼtぎ<MN>を rげる@"

BarrierDescription:
	db   "mのまuに wべを Üyりだし"
	next "ぼtぎ<MN>を グ-lörげる@"

LightScreenDescription:
	db   "ひwりのwべを Üyり öyし<PK>"
	next "こtげxの ダa-ジを vわmる@"

HazeDescription:
	db   "yろsxりが wらだを vvs"
	next "wらだの sじ<MN>tを röにrどす@"

ReflectDescription:
	db   "ひwりのwべを Üyり ぶÜり"
	next "こtげxの ダa-ジを vわmる@"

FocusEnergyDescription:
	db   "こtげxに xrsを こmä"
	next "HりSqFg(mTを でsすyする@"

BideDescription:
	db   "2-3P-l こtげxに Äuä"
	next "tzÄダa-ジを ばsにしäwuす@"

MetronomeDescription:
	db   "tびを ふ←ä のtを しげxしä"
	next "sろんü jザを flダ]でyりだす@"

MirrorMoveDescription:
	db   "äxの わざを まねしä "
	next "vüじわざで äxを こtげx@"

SelfdestructDescription:
	db   "äxに だsダa-ジを rÄuるが"
	next "Üwtö せんötふのtに üる@"

EggBombDescription:
	db   "P;ゴを vrs←xり üげÜzä"
	next "äxを こtげx@"

LickDescription:
	db   "üがsしÄで ümまわしä こtげx"
	next "äxを ;(させるこöがrる@"

SmogDescription:
	db   "はsxガMを ふxwzä こtげx"
	next "äxに どyをrÄuるこöがrる@"

SludgeDescription:
	db   "へドiを üげÜzä こtげx"
	next "äxに どyをrÄuるこöがrる@"

BoneClubDescription:
	db   "äにr←Ä :Xで äxを こtげx"
	next "äxを ひるませるこöがrる@"

FireBlastDescription:
	db   "だsの rじが すべäを sxÜyす"
	next "äxを szどさせるこöがrる@"

WaterfallDescription:
	db   "Äxを さwのぼるvtü sxvsで"
	next "äxに ö←しんする@"

ClampDescription:
	db   "2-5P-lのrsだ äxを"
	next "wらに はさdこんでしまt @"

SwiftDescription:
	db   "ぜ←Äsに vzられüs ほしがÄの"
	next "こtせんを lすtに は←しする@"

SkullBashDescription:
	db   "1P-lmで rÄまを ひ←こmä"
	next "ÜぎのP-lで äxを こtげx@"

SpikeCannonDescription:
	db   "するどsZりを äxに は←ししä"
	next "2-5ws れんぞyで こtげx@"

ConstrictDescription:
	db   "2-5P-lのrsだ üがswらだs"
	next "RgをÜw←ä äxを しmÜzる@"

AmnesiaDescription:
	db   "s←し<PK>ん üにwを わすれるこöで"
	next "öyし<PK>ぼtぎ<MN>を グ-lörげる@"

KinesisDescription:
	db   "äxの mを Mプ-lに lzさせä"
	next "msÖ<PK>tりÜを さげさせる@"

SoftboiledDescription:
	db   "GズÜsÄ wらだを Äsり<MN>yの"
	next "はんぶんだz wsふyする@"

HiJumpKickDescription:
	db   "ジnlプしÄ sxvsで ひざげりを"
	next "yりだす はずすö ダa-ジをtzる@"

GlareDescription:
	db   "vüwの rvtで äxを swyし"
	next "vびuさせä ;(させäしまt@"

DreamEaterDescription:
	db   "äxに rÄuÄ ダa-ジの"
	next "はんぶん Äsり<MN>yを wsふyする@"

PoisonGasDescription:
	db   "どyガMを äxに ふxwzä"
	next "どyをrÄuる@"

BarrageDescription:
	db   "まるsrのを äxに üげÜzä"
	next "2-5ws れんぞyで こtげx@"

LeechLifeDescription:
	db   "äxに rÄuÄ ダa-ジの"
	next "はんぶん Äsり<MN>yを wsふyする@"

LovelyKissDescription:
	db   "こわs wvで GMを せまる"
	next "GMされるö ねl←äしまt@"

SkyAttackDescription:
	db   "1P-lmで じyäんを さがし"
	next "ÜぎのP-lで äxを こtげx@"

TransformDescription:
	db   "äxの ポIblö vüじ すがÄに"
	next "さsぼtを へんwさせ へんしんする@"

BubbleDescription:
	db   "rわを ふxwzä こtげx"
	next "äxの すばsさを さげるこöがrる@"

DizzyPunchDescription:
	db   "vsこどtじに パlQで こtげx"
	next "äxを こんらんさせるこöがrる@"

SporeDescription:
	db   "さsdんこtwのrる ほtしを"
	next "ふりまx äxを ねlらせる@"

FlashDescription:
	db   "Üvs ひwりで mを yらませä"
	next "äxの msÖ<PK>tりÜを さげさせる@"

PsywaveDescription:
	db   "äxに 1-hべg×1<5の"
	next "ダa-ジを flダ]で rÄuる@"

SplashDescription:
	db   "はねるだzで üにrvこらüs…@"

AcidArmorDescription:
	db   "wらだを uxじ<MN>tに へんwさせä"
	next "ぼtぎ<MN>を グ-lörげる@"

CrabhammerDescription:
	db   "ZK[を äxに ÄÄxÜzる"
	next "HりSqFg(mTが でsすs@"

ExplosionDescription:
	db   "äxに だsダa-ジを rÄuるが"
	next "Üwtö せんötふのtに üる@"

FurySwipesDescription:
	db   "äxを するどsRaで ひ←wsä"
	next "2-5ws れんぞyで こtげx@"

BonemerangDescription:
	db   ":Xを üげÜzä sxö wuりで"
	next "2ws れんぞyで こtげx@"

RestDescription:
	db   "2P-l ねl←ä Äsり<MN>yö"
	next "wらだのsじ<MN>tを wsふyする@"

RockSlideDescription:
	db   "vvxü sわを üげÜzる"
	next "äxを ひるませるこöがrる@"

HyperFangDescription:
	db   "するどsまuばで äxを こtげx"
	next "ひるませるこöがrる@"

SharpenDescription:
	db   "ポりゴlを へらし FHFHにü←ä"
	next "こtげxを rげる@"

ConversionDescription:
	db   "じぶんに SHMQn-を はりÜzä"
	next "äxö vüじ ぞyせsに wわる@"

TriAttackDescription:
	db   "3し<PK>るsの こtせんを"
	next "1Üにまömä äxに は←しする@"

SuperFangDescription:
	db   "するどsまuばで こtげxしä"
	next "äxの Äsり<MN>yを はんぶんにする@"

SlashDescription:
	db   "するどsF;s Raüどで こtげx"
	next "HりSqFg(mTが でsすs@"

SubstituteDescription:
	db   "Äsり<MN>yの 4ぶんの1を Üw←ä"
	next "じぶんの ぶんしんをだす@"

StruggleDescription:
	db   "わざポBlTがüyüるö でるわざ"
	next "じぶんrすこし ダa-ジをtzる@"

SketchDescription:
	db   "äxが Üw←Äわざを MImQしä"
	next "そのわざを じぶんのrのに する@"

TripleKickDescription:
	db   "äxを 3ws れんぞyで こtげx"
	next "räるÄびに ダa-ジが rがる@"

ThiefDescription:
	db   "こtげxの さsÖ<PK>tに すxをdä"
	next "äxが r←äsる どtぐを ぬすl@"

SpiderWebDescription:
	db   "XバXバöしÄ söを wらませä"
	next "äxを にげられüy しäしまt@"

MindReaderDescription:
	db   "äxの tごxを こころで wんじä"
	next "Üぎの こtげxを wüらず räる@"

NightmareDescription:
	db   "äxが ねäるrsだ Äsり<MN>yを"
	next "まsP-l 8ぶんの1 へらしäsy@"

FlameWheelDescription:
	db   "ほのvを まö←ä ö←しんする"
	next "äxを szどさせるこöがrる@"

SnoreDescription:
	db   "ねäsるöxだz Üwuる わざ"
	next "すごssびxで äxを こtげx@"

NailDownDescription:
	db   "じぶんを こtげxするこöで äxに"
	next "まsP-l ダa-ジを rÄuる@"

FlailDescription:
	db   "Äsり<MN>yが すyüsほど"
	next "äxに vvxüダa-ジを rÄuる@"

Conversion2Description:
	db   "äxに SHMQn-を はりÜzä"
	next "ぞyせsを flダ]でwuäしまt@"

CoinHurlDescription:
	db   "vwねを Üw←ä äxを こtげx"
	next "wsぬしが りmQüほど Üvsjザ@"

CottonSporeDescription:
	db   "ほtしを まöわりÜwせ äxにの"
	next "ぼtぎ<MN>を ガHmöさげさせる@"

ReversalDescription:
	db   "Äsり<MN>yが すyüsほど"
	next "äxに vvxüダa-ジを rÄuる@"

SpiteDescription:
	db   "さsごに tzÄ わざを tらんで "
	next "その わざポBlTを へらしäしまt@"

PowderSnowDescription:
	db   "txを wぜにのせä こtげx"
	next "äxを こvらせるこöがrる@"

ProtectDescription:
	db   "ÜぎのP-lの こtげxを tzüs@"

MachPunchDescription:
	db   "rのすごsはsさで パlQをyりだし"
	next "wüらず せんせsこtげxする@"

ScaryFaceDescription:
	db   "こわswvで äxを vびuさせä "
	next "ぼtぎ<MN>を ガHmöさげさせる@"

FaintAttackDescription:
	db   "äxを tだんさせä Öwづx"
	next "vzられüs こtげxを yりだす@"

SweetKissDescription:
	db   "wわss wvで GMを せまる"
	next "GMされるö こんらんしäしまt@"

BellyDrumDescription:
	db   "vüwを ÄÄsä äxを swy"
	next "こtげxを グ-lörげる@"

SludgeBombDescription:
	db   "へドiを üげÜzä こtげx"
	next "äxに どyをrÄuるこöがrる@"

MudSlapDescription:
	db   "äxの wvüどに ドiをwzä "
	next "msÖ<PK>tりÜを さげさせる@"

OctazookaDescription:
	db   "すdの wÄまりを は←ししä"
	next "msÖ<PK>tりÜを さげさせる @"

SpikesDescription:
	db   "äxが にげるöxに わüを しwz"
	next "こtÄsしÄ äxを こtげxする@"

ZapCannonDescription:
	db   "rÄりにysが ダa-ジは vvxs"
	next "rÄれば wüらず ;(させる@"

ForesightDescription:
	db   "ゴ-MTPBプの äxに "
	next "Y-;gPBプの わざが rÄる@"

DestinyBondDescription:
	db   "このわざの röに Ävされるö"
	next "äxr せんötふのtにüる@"

PerishSongDescription:
	db   "xsÄ ポIblは 3P-lごに"
	next "せんötふのtに ü←äしまt@"

SynchronizeDescription:
	db   "LlHiじ<MN>tÄsに üるö äxr"
	next "vüじ ダa-ジを tzるvtにüる@"

DetectDescription:
	db   "äxの tごxを dxるこöで"
	next "Üぎの こtげxを wüらずräる@"

BoneLockDescription:
	db   "äにr←Ä :Xで 2-5ws "
	next "れんぞyで äxを こtげxする@"

LockOnDescription:
	db   "äxに し<MN>tじ<PK>んを rわせä"
	next "Üぎの こtげxを wüらずräる@"

OutrageDescription:
	db   "2-3P-lのrsだ rばれÜづzる"
	next "rばれÄröは こんらんしäしまt@"

SandstormDescription:
	db   "すürらしを は←せsさせä"
	next "まsP-l ダa-ジを rÄuる@"

GigaDrainDescription:
	db   "äxに rÄuÄ ダa-ジの"
	next "はんぶん Äsり<MN>yを wsふyする@"

EndureDescription:
	db   "ÜぎのP-lで こtげxを tzär"
	next "wららず Äsり<MN>yが 1のこる@"

CharmDescription:
	db   "wわsyrまuä äxを tだんさせ"
	next "こtげxを ガHmöさげさせる @"

RolloutDescription:
	db   "5P-lのrsだ äxを こtげx"
	next "räるÄびに ダa-ジが rがる@"

FalseSwipeDescription:
	db   "wüらず Äsり<MN>yが 1のこるvt"
	next "äwげんしä こtげx@"

SwaggerDescription:
	db   "äxを vこらせä こんらんさせるが"
	next "こtげxr グ-lö rげäしまt@"

MilkDrinkDescription:
	db   "GズÜsÄ wらだを Äsり<MN>yの"
	next "はんぶんだz wsふyする@"

SparkDescription:
	db   "でんxを まö←ä ö←しんする"
	next "äxを ;(させるこöがrる@"

FuryCutterDescription:
	db   "するどsF;s Raüどで äxを"
	next "2ws れんぞyで こtげx@"

SteelWingDescription:
	db   "Üばさを vvxy ひろげä"
	next "そのまま äxに ÄsrÄりする@"

StalkerDescription:
	db   "äxを じ-←ö däsるö üぜw"
	next "äxは にげられüy ü←äしまt@"

AttractDescription:
	db   "EMüら aMに aMüら EMに"
	next "こtげxが でxüyü←äしまt@"

SleepTalkDescription:
	db   "ねäsるöxだz Üwuる わざ"
	next "flダ]で じぶんのわざを yりだす@"

BellChimeDescription:
	db   "ここÖvs すずのねを xwせä"
	next "すべäの じ<MN>tÄsを wsふyする@"

ReturnDescription:
	db   "vyしäyれる wsぬしの Ämに"
	next "ぜんり<MN>yで äxを こtげx@"

PresentDescription:
	db   "äxに ばyだんを プhゼlTする"
	next "Äまに wsふyしäしまtこöがrる@"

FrustrationDescription:
	db   "lごs しtÖの tさばらしに "
	next "äxを ぜんり<MN>yで こtげx@"

SafeguardDescription:
	db   "ふしぎü Öwらで まrられä"
	next "öyし<PK> じ<MN>tÄsに üらüyüる@"

PainSplitDescription:
	db   "äxö じぶんの Äsり<MN>yを"
	next "Äしä それを üwvy わzる@"

SacredFireDescription:
	db   "しんぴäxü ほのvで こtげx"
	next "äxを ひるませるこöがrる@"

MagnitudeDescription:
	db   "じmんを tらしä äxを こtげx"
	next "ダa-ジは flダ]で wわる@"

DynamicpunchDescription:
	db   "rÄりにysが ダa-ジは vvxs"
	next "rÄれば wüらず こんらんさせる@"

MegaphoneDescription:
	db   "すごsvöで äxの xをÖらせä "
	next "öyし<PK>こtげxを さげさせる@"

DragonbreathDescription:
	db   "yÖwら rのすごs sxをはsä"
	next "äxを こtげx@"

BatonPassDescription:
	db   "Üswこtwを のこしÄまま"
	next "ほwの ポIblö sれwわる@"

EncoreDescription:
	db   "äxが さsごに Üw←Ä わざを"
	next "2-5ws れんぞyで ださせる@"

PursuitDescription:
	db   "äxが にげるöxに Üwtö"
	next "だsダa-ジを rÄuるこöがでxる@"

RapidSpinDescription:
	db   "wらだを はsy wsäんさせä"
	next "äxを こtげx@"

TemptDescription:
	db   "äxに DKをüげä xを そらせä"
	next "äxの wsひりÜを さげさせる@"

IronTailDescription:
	db   "wÄs Lmポで äxを こtげx"
	next "äxの ぼtぎ<MN>を さげるこöがrる@"

RockHeadDescription:
	db   "wÄs rÄまで äxを こtげx"
	next "äxを ひるませるこöがrる@"

VitalThrowDescription:
	db   "こtげxを tzずに こtげxでxる"
	next "はずれるö だsダa-ジを tzる@"

MorningSunDescription:
	db   "Äsり<MN>yを wsふyする"
	next "じwんで wsふyり<MN>tが wわる@"

SynthesisDescription:
	db   "Äsり<MN>yを wsふyする"
	next "じwんで wsふyり<MN>tが wわる@"

MoonlightDescription:
	db   "Äsり<MN>yを wsふyする"
	next "じwんで wsふyり<MN>tが wわる@"

HiddenPowerDescription:
	db   "ポIblにv←ä äxに rÄuる"
	next "ダa-ジの り<MN>tが へんwする@"

CrossCutterDescription:
	db   "ZK[を こtさ させä こtげx"
	next "HりSqFg(mTが でsすs@"

TwisterDescription:
	db   "rのすごs wぜを vこしä"
	next "äxを こtげx@"

RainDanceDescription:
	db   "5P-lのrsだ dずPBプの"
	next "わざの sり<MN>yが rがる@"

SunnyDayDescription:
	db   "5P-lのrsだ ほのvPBプの"
	next "わざの sり<MN>yが rがる@"

F2Description:
	db   "JalTさyせsÖ<PK>t@"

F3Description:
	db   "JalTさyせsÖ<PK>t@"

F4Description:
	db   "JalTさyせsÖ<PK>t@"

UprootDescription:
	db   "äxを Üwんで ほtりüげä"
	next "だsダa-ジを rÄuる@"

WindRideDescription:
	db   "wぜö örに äxに ÄsrÄり"
	next "HりSqFg(mTが でsすs@"

WaterSportDescription:
	db   "JalTさyせsÖ<PK>t@"

StrongArmDescription:
	db   "ふös tでで äxを こtげx"
	next "こtげxが rがるこöがrる@"

BrightMossDescription:
	db   "rÄりを rwるyしä"
	next "わざの msÖ<PK>tりÜを rげる@"

WhirlpoolDescription:
	db   "2-5P-lのrsだ äxを"
	next "tずの Ö<PK>tしんに öじこmる@"

BounceDescription:
	db   "はねるだzで üにrvこらüs…@"
