ItemDescriptions::
	dw MasterBallDescription
	dw UltraBallDescription
	dw Item03Description
	dw GreatBallDescription
	dw PokeBallDescription
	dw TownMapDescription
	dw BicycleDescription
	dw MoonStoneDescription
	dw AntidoteDescription
	dw BurnHealDescription
	dw IceHealDescription
	dw AwakeningDescription
	dw ParlyzHealDescription
	dw FullRestoreDescription
	dw MaxPotionDescription
	dw HyperPotionDescription
	dw SuperPotionDescription
	dw PotionDescription
	dw EscapeRopeDescription
	dw RepelDescription
	dw MaxElixerDescription
	dw FireStoneDescription
	dw ThunderstoneDescription
	dw WaterStoneDescription
	dw Item19Description
	dw HPUpDescription
	dw ProteinDescription
	dw IronDescription
	dw CarbosDescription
	dw Item1EDescription
	dw CalciumDescription
	dw RareCandyDescription
	dw XAccuracyDescription
	dw LeafStoneDescription
	dw Item23Description
	dw NuggetDescription
	dw PokeDollDescription
	dw FullHealDescription
	dw ReviveDescription
	dw MaxReviveDescription
	dw GuardSpecDescription
	dw SuperRepelDescription
	dw MaxRepelDescription
	dw DireHitDescription
	dw Item2DDescription
	dw FreshWaterDescription
	dw SodaPopDescription
	dw LemonadeDescription
	dw XAttackDescription
	dw Item32Description
	dw XDefendDescription
	dw XSpeedDescription
	dw XSpecialDescription
	dw CoinCaseDescription
	dw ItemfinderDescription
	dw PokeFluteDescription
	dw ExpShareDescription
	dw OldRodDescription
	dw GoodRodDescription
	dw Item3CDescription
	dw SuperRodDescription
	dw PPUpDescription
	dw EtherDescription
	dw MaxEtherDescription
	dw ElixerDescription
	dw MysticPetalDescription
	dw WhiteFeatherDescription
	dw ConfuseClawDescription
	dw WisdomOrbDescription
	dw SteelShellDescription
	dw UpGradeDescription
	dw StrangeThreadDescription
	dw BigLeafDescription
	dw QuickNeedleDescription
	dw Item4BDescription
	dw SharpStoneDescription
	dw BlackFeatherDescription
	dw SharpFangDescription
	dw SnakeskinDescription
	dw ElectricPouchDescription
	dw ToxicNeedleDescription
	dw KingsRockDescription
	dw StrangePowerDescription
	dw LifeTagDescription
	dw PoisonFangDescription
	dw CordycepsDescription
	dw DragonFangDescription
	dw SilverpowderDescription
	dw DiggingClawDescription
	dw Item5ADescription
	dw AmuletCoinDescription
	dw MigraineSeedDescription
	dw CounterCuffDescription
	dw TalismanTagDescription
	dw StrangeWaterDescription
	dw TwistedspoonDescription
	dw AttackNeedleDescription
	dw PowerBracerDescription
	dw HardStoneDescription
	dw Item64Description
	dw JigglingBalloonDescription
	dw FireManeDescription
	dw SlowpoketailDescription
	dw EarthDescription
	dw StickDescription
	dw FleeFeatherDescription
	dw IceFangDescription
	dw FossilShardDescription
	dw GrossGarbageDescription
	dw BigPearlDescription
	dw ChampionBeltDescription
	dw TagDescription
	dw SpellTagDescription
	dw FiveYenCoinDescription
	dw GuardThreadDescription
	dw StimulusOrbDescription
	dw CalmBerryDescription
	dw ThickClubDescription
	dw FocusOrbDescription
	dw Item78Description
	dw DetectOrbDescription
	dw LongTongueDescription
	dw LottoTicketDescription
	dw EverstoneDescription
	dw SharpHornDescription
	dw LuckyEggDescription
	dw LongVineDescription
	dw MomsLoveDescription
	dw SmokescreenItemDescription
	dw WetHornDescription
	dw SkateboardDescription
	dw CrimsonJewelDescription
	dw InvisibleWallDescription
	dw SharpScytheDescription
	dw Item87Description
	dw IceBikiniDescription
	dw ThunderFangDescription
	dw FireClawDescription
	dw TwinHornsDescription
	dw SpikeDescription
	dw BerryDescription
	dw AppleDescription
	dw MetalCoatDescription
	dw PrettyTailDescription
	dw WaterTailDescription
	dw LeftoversDescription
	dw IceWingDescription
	dw ThunderWingDescription
	dw FireWingDescription
	dw Item96Description
	dw DragonScaleDescription
	dw BerserkGeneDescription
	dw HeartStoneDescription
	dw FireTailDescription
	dw ThunderTailDescription
	dw SacredAshDescription
	dw TMHolderDescription
	dw MailDescription
	dw BallHolderDescription
	dw BagDescription
	dw ImportantBagDescription
	dw PoisonStoneDescription
	dw ItemA3Description
	dw ItemA4Description
	dw ItemA5Description
	dw ItemA6Description
	dw ItemA7Description
	dw ItemA8Description
	dw ItemA9Description
	dw ItemAADescription
	dw ItemABDescription
	dw ItemACDescription
	dw ItemADDescription
	dw ItemAEDescription
	dw ItemAFDescription
	dw ItemB0Description
	dw ItemB1Description
	dw ItemB2Description
	dw ItemB3Description
	dw ItemB4Description
	dw ItemB5Description
	dw ItemB6Description
	dw ItemB7Description
	dw ItemB8Description
	dw ItemB9Description
	dw ItemBADescription
	dw ItemBBDescription
	dw ItemBCDescription
	dw ItemBDDescription
	dw ItemBEDescription
	dw ItemBFDescription
	dw ItemC0Description
	dw ItemC1Description
	dw ItemC2Description
	dw ItemC3Description
	dw TM01Description
	dw TM02Description
	dw TM03Description
	dw TM04Description
	dw ItemC8Description
	dw TM05Description
	dw TM06Description
	dw TM07Description
	dw TM08Description
	dw TM09Description
	dw TM10Description
	dw TM11Description
	dw TM12Description
	dw TM13Description
	dw TM14Description
	dw TM15Description
	dw TM16Description
	dw TM17Description
	dw TM18Description
	dw TM19Description
	dw TM20Description
	dw TM21Description
	dw TM22Description
	dw TM23Description
	dw TM24Description
	dw TM25Description
	dw TM26Description
	dw TM27Description
	dw TM28Description
	dw ItemE1Description
	dw TM29Description
	dw TM30Description
	dw TM31Description
	dw TM32Description
	dw TM33Description
	dw TM34Description
	dw TM35Description
	dw TM36Description
	dw TM37Description
	dw TM38Description
	dw TM39Description
	dw TM40Description
	dw TM41Description
	dw TM42Description
	dw TM43Description
	dw TM44Description
	dw TM45Description
	dw TM46Description
	dw TM47Description
	dw TM48Description
	dw TM49Description
	dw TM50Description
	dw HM01Description
	dw HM02Description
	dw HM03Description
	dw HM04Description
	dw HM05Description
	dw HM06Description
	dw HM07Description
	dw ItemFFDescription

MasterBallDescription:
	db   "ポIblを Üwまuるこöが でxる@"

UltraBallDescription:
	db   "ポIblを Üwまuるこöが でxる@"

Item03Description:
	db   "?"
	next "?@"

GreatBallDescription:
	db   "ポIblを Üwまuるこöが でxる@"

PokeBallDescription:
	db   "ポIblを Üwまuるこöが でxる@"

TownMapDescription:
	db   ";mプを dるこöが でxる@"

BicycleDescription:
	db   "2ばsの はsさで sどtでxる"
	next "しÜüsでは のるこöが でxüs@"

MoonStoneDescription:
	db   "öyäsの ポIblを しんwさせる@"

AntidoteDescription:
	db   "どy じ<MN>tÄswら wsふyする@"

BurnHealDescription:
	db   "szど じ<MN>tÄswら wsふyする@"

IceHealDescription:
	db   "こvり じ<MN>tÄswら wsふyする@"

AwakeningDescription:
	db   "ねlり じ<MN>tÄswら wsふyする@"

ParlyzHealDescription:
	db   ";( じ<MN>tÄswら wsふyする@"

FullRestoreDescription:
	db   "すべäの MS-PMsじ<MN>tö"
	next "Äsり<MN>yを ぜんwsふyする  @"

MaxPotionDescription:
	db   "Äsり<MN>yを ぜんwsふyする  @"

HyperPotionDescription:
	db   "Äsり<MN>yを200 wsふyする  @"

SuperPotionDescription:
	db   "Äsり<MN>yを50 wsふyする  @"

PotionDescription:
	db   "Äsり<MN>yを20 wsふyする  @"

EscapeRopeDescription:
	db   "ダlジplwら ぬzだす@"

RepelDescription:
	db   "100ぽのrsだ vわs ポIblö"
	next "DlFClTしüyüる@"

MaxElixerDescription:
	db   "ポIbl 1Äsの"
	next "ピ-ピ- すべäを ぜんwsふyする@"

FireStoneDescription:
	db   "öyäsの ポIblを しんwさせる@"

ThunderstoneDescription:
	db   "öyäsの ポIblを しんwさせる@"

WaterStoneDescription:
	db   "öyäsの ポIblを しんwさせる@"

Item19Description:
	db   "?"
	next "?@"

HPUpDescription:
	db   "Äsり<MN>yの さsだsÖを ふsす@"

ProteinDescription:
	db   "こtげxの xそポBlTを rげる@"

IronDescription:
	db   "ぼtぎ<MN>の xそポBlTを rげる@"

CarbosDescription:
	db   "すばsさの xそポBlTを rげる@"

Item1EDescription:
	db   "?"
	next "?@"

CalciumDescription:
	db   "öyし<PK>の xそポBlTを rげる@"

RareCandyDescription:
	db   "ポIblの hべgを 1Ürげる@"

XAccuracyDescription:
	db   "しvtしÄ せんötÖ<PK>tだz"
	next "msÖ<PK>tりÜが rがる@"

LeafStoneDescription:
	db   "öyäsの ポIblを しんwさせる@"

Item23Description:
	db   "?"
	next "?@"

NuggetDescription:
	db   "xんで でxÄ P;"
	next "Äwy tれる@"

PokeDollDescription:
	db   "DlFClTしÄ ポIblwら"
	next "wüらず にげられる@"

FullHealDescription:
	db   "すべäの MS-PMsじ<MN>tの"
	next "じ<MN>tÄswら wsふyする@"

ReviveDescription:
	db   "Äsり<MN>yが はんぶんで"
	next "ひんしじ<MN>tÄswら wsふyする@"

MaxReviveDescription:
	db   "Äsり<MN>yが ぜんwsで"
	next "ひんしじ<MN>tÄswら wsふyする@"

GuardSpecDescription:
	db   "しvtしÄ せんötÖ<PK>tだz"
	next "öyし<PK>ぼtぎ<MN>が rがる@"

SuperRepelDescription:
	db   "200ぽのrsだ vわs ポIblö"
	next "DlFClTしüyüる@"

MaxRepelDescription:
	db   "250ぽのrsだ vわs ポIblö"
	next "DlFClTしüyüる@"

DireHitDescription:
	db   "しvtしÄ せんötÖ<PK>tだz"
	next "HりSqFgりÜが rがる@"

Item2DDescription:
	db   "?"
	next "?@"

FreshWaterDescription:
	db   "Äsり<MN>yを50 wsふyする  @"

SodaPopDescription:
	db   "Äsり<MN>yを60 wsふyする  @"

LemonadeDescription:
	db   "Äsり<MN>yを80 wsふyする  @"

XAttackDescription:
	db   "しvtしÄ せんötÖ<PK>tだz"
	next "こtげxが rがる@"

Item32Description:
	db   "?"
	next "?@"

XDefendDescription:
	db   "しvtしÄ せんötÖ<PK>tだz"
	next "ぼtぎ<MN>が rがる@"

XSpeedDescription:
	db   "しvtしÄ せんötÖ<PK>tだz"
	next "すばsさが rがる@"

XSpecialDescription:
	db   "しvtしÄ せんötÖ<PK>tだz"
	next "öyし<PK>こtげxが rがる@"

CoinCaseDescription:
	db   "r←äsるö JBlを "
	next "9999まsまで rÜこöが でxる@"

ItemfinderDescription:
	db   "wyされÄ どtぐが "
	next "がmんüsにrるö vöがüる@"

PokeFluteDescription:
	db   "ねl←äsる ポIblを vこす@"

ExpShareDescription:
	db   "ÄÄwわüw←Ä ポIblにr"
	next "zszんÖが ふりわzられる@"

OldRodDescription:
	db   "ポIblが Üれる@"

GoodRodDescription:
	db   "ポIblが Üれる@"

Item3CDescription:
	db   "?"
	next "?@"

SuperRodDescription:
	db   "ポIblが Üれる@"

PPUpDescription:
	db   "わざポBlTの さsだsÖが rがる@"

EtherDescription:
	db   "ポIbl1Äsの 1Üの "
	next "わざポBlTを 10wsふyする  @"

MaxEtherDescription:
	db   "ポIbl1Äsの 1Üの"
	next "わざポBlTを ぜんwsふyする  @"

ElixerDescription:
	db   "ポIbl1Äsの すべäの"
	next "わざポBlTを 10wsふyする  @"

MysticPetalDescription:
	db   "そtびするö yさPBプの "
	next "わざのsり<MN>yを vわmられる@"

WhiteFeatherDescription:
	db   "そtびするö ひこtPBプの"
	next "わざのsり<MN>yを vわmられる@"

ConfuseClawDescription:
	db   "そtびするö せんötの まuに"
	next "äxに ダa-ジを rÄuる@"

WisdomOrbDescription:
	db   "そtびするö "
	next "öyし<PK>ぼtぎ<MN>が 10rがる@"

SteelShellDescription:
	db   "そtびするö "
	next "ぼtぎ<MN>が 10rがる@"

UpGradeDescription:
	db   "そtびするö "
	next "すべäの のtり<MN>yが 5rがる@"

StrangeThreadDescription:
	db   "そtびするö"
	next "äxの こtげxを vzるこöがrる@"

BigLeafDescription:
	db   "そtびするö yさPBプの "
	next "わざのsり<MN>yが rがる@"

QuickNeedleDescription:
	db   "そtびするö"
	next "せんせsこtげx するこöがrる@"

Item4BDescription:
	db   "?"
	next "?@"

SharpStoneDescription:
	db   "そtびするö sわPBプの "
	next "わざのsり<MN>yが rがる@"

BlackFeatherDescription:
	db   "そtびするö ひこtPBプの "
	next "わざのsり<MN>yが rがる@"

SharpFangDescription:
	db   "そtびするö Y-;gPBプの "
	next "わざのsり<MN>yが rがる@"

SnakeskinDescription:
	db   "そtびするö "
	next "どy じ<MN>tÄsに üらüs@"

ElectricPouchDescription:
	db   "そtびするö でんxPBプの "
	next "わざのsり<MN>yを vわmられる@"

ToxicNeedleDescription:
	db   "そtびするö どyPBプの "
	next "わざのsり<MN>yが rがる@"

KingsRockDescription:
	db   "そtびするö"
	next "Äまに äxが ひるlこöがrる@"

StrangePowerDescription:
	db   "そtびするö "
	next "すべäの PBプこtwが lこt@"

LifeTagDescription:
	db   "そtびするö せんötごに"
	next "ひんし じ<MN>tÄswら wsふyする@"

PoisonFangDescription:
	db   "そtびするö どyPBプの"
	next "わざのsり<MN>yが rがる@"

CordycepsDescription:
	db   "り←ぱü GYJ"
	next "Äwy tれる@"

DragonFangDescription:
	db   "そtびするö ドfゴlPBプの"
	next "わざのsり<MN>yが rがる@"

SilverpowderDescription:
	db   "そtびするö lしPBプの "
	next "わざのsり<MN>yを vわmられる@"

DiggingClawDescription:
	db   "そtびするö せんötsがsで"
	next "rüをほるが Üwuるvtにüる@"

Item5ADescription:
	db   "?"
	next "?@"

AmuletCoinDescription:
	db   "そtびするö "
	next "rらuる vwねが 2ばs@"

MigraineSeedDescription:
	db   "そtびするö DMパ-PBプの"
	next "わざのsり<MN>yが rがる@"

CounterCuffDescription:
	db   "そtびするö 4ぶんの1で"
	next "äxに はんげxする @"

TalismanTagDescription:
	db   "そtびするö "
	next "DlFClT しにyyüる@"

StrangeWaterDescription:
	db   "そtびするö dずPBプの "
	next "わざのsり<MN>yを vわmられる@"

TwistedspoonDescription:
	db   "そtびするö DMパ-PBプの "
	next "わざのsり<MN>yを vわmられる@"

AttackNeedleDescription:
	db   "そtびするö lしPBプの"
	next "わざのsり<MN>yが rがる@"

PowerBracerDescription:
	db   "そtびするö wyötPBプの "
	next "わざのsり<MN>yが rがる@"

HardStoneDescription:
	db   "そtびするö sわPBプの "
	next "わざのsり<MN>yを vわmられる@"

Item64Description:
	db   "?"
	next "?@"

JigglingBalloonDescription:
	db   "そtびするö Y-;gPBプの "
	next "わざのsり<MN>yを vわmられる@"

FireManeDescription:
	db   "そtびするö ほのvPBプの "
	next "わざのsり<MN>yを vわmられる@"

SlowpoketailDescription:
	db   "öär vsしs"
	next "Äwy tれる@"

EarthDescription:
	db   "そtびするö"
	next ";( じ<MN>tÄsに üらüs@"

StickDescription:
	db   "そtびするö Y-;gPBプの "
	next "わざのsり<MN>yが rがる@"

FleeFeatherDescription:
	db   "そtびするö 1P-l wzüsで"
	next "ほwの ポIblö こtÄsでxる@"

IceFangDescription:
	db   "そtびするö こvりPBプの "
	next "わざのsり<MN>yが rがる@"

FossilShardDescription:
	db   "そtびするö じmんPBプの "
	next "わざのsり<MN>yを vわmられる@"

GrossGarbageDescription:
	db   "そtびするö どyPBプの "
	next "わざのsり<MN>yを vわmられる@"

BigPearlDescription:
	db   "xれsü しんじ<PK>"
	next "Äwy tれる@"

ChampionBeltDescription:
	db   "そtびするö wyötPBプの "
	next "わざのsり<MN>yを vわmられる@"

TagDescription:
	db   "そtびするö ゴ-MTPBプの "
	next "わざのsり<MN>yを vわmられる@"

SpellTagDescription:
	db   "そtびするö "
	next "DlFClT しsすyüる@"

FiveYenCoinDescription:
	db   "そtびするö DMパ-PBプの "
	next "わざのsり<MN>yを vわmられる@"

GuardThreadDescription:
	db   "そtびするö lしPBプの "
	next "わざのsり<MN>yを vわmられる@"

StimulusOrbDescription:
	db   "そtびするö "
	next "ねlり じ<MN>tÄsに üらüs@"

CalmBerryDescription:
	db   "そtびするö "
	next "こんらん じ<MN>tÄsに üらüs@"

ThickClubDescription:
	db   "そtびするö じmんPBプの "
	next "わざのsり<MN>yが rがる@"

FocusOrbDescription:
	db   "そtびするö"
	next "xぜÜ しüsで Äuるこöがrる@"

Item78Description:
	db   "?"
	next "?@"

DetectOrbDescription:
	db   "そtびするö"
	next "äxの こtげxを vzるこöがrる@"

LongTongueDescription:
	db   "そtびするö"
	next "ポIblの ほwyりÜが rがる@"

LottoTicketDescription:
	db   "ふyびxが でxる@"

EverstoneDescription:
	db   "そtびするö"
	next "ポIblが しんw しüyüる@"

SharpHornDescription:
	db   "そtびするö "
	next "こtげxが 10rがる@"

LuckyEggDescription:
	db   "そtびするö "
	next "rらuる zszんÖが 2ばs@"

LongVineDescription:
	db   "そtびするö"
	next "ポIblの ほwyりÜが rがる@"

MomsLoveDescription:
	db   "そtびするö rるyÄびに  "
	next "Äsり<MN>yが1 wsふyする@"

SmokescreenItemDescription:
	db   "そtびするö "
	next "DlFClTしÄäxwら にげられる@"

WetHornDescription:
	db   "そtびするö dずPBプの "
	next "わざのsり<MN>yが rがる@"

SkateboardDescription:
	db   "2ばsの はsさで sどtでxる"
	next "しÜüsでr のるこöが でxる@"

CrimsonJewelDescription:
	db   "rws ほtせx"
	next "Äwy tれる@"

InvisibleWallDescription:
	db   "そtびするö öyし<PK>こtげxの"
	next "ダa-ジが はんぶんにüる@"

SharpScytheDescription:
	db   "そtびするö"
	next "HりSqFgが でsすyüる@"

Item87Description:
	db   "?"
	next "?@"

IceBikiniDescription:
	db   "そtびするö こvりPBプの "
	next "わざのsり<MN>yを vわmられる@"

ThunderFangDescription:
	db   "そtびするö でんxPBプの "
	next "わざのsり<MN>yが rがる@"

FireClawDescription:
	db   "そtびするö ほのvPBプの "
	next "わざのsり<MN>yが rがる@"

TwinHornsDescription:
	db   "そtびするö "
	next "こtげxが 10rがる@"

SpikeDescription:
	db   "そtびするö ゴ-MTPBプの "
	next "わざのsり<MN>yが rがる@"

BerryDescription:
	db   "Äsり<MN>yを20 wsふyする  @"

AppleDescription:
	db   "Äsり<MN>yを50 wsふyする  @"

MetalCoatDescription:
	db   "そtびするö ふÜtこtげxの"
	next "ダa-ジが はんぶんにüる@"

PrettyTailDescription:
	db   "そtびするö "
	next "どy じ<MN>tÄsに üらüs@"

WaterTailDescription:
	db   "そtびするö "
	next "szど じ<MN>tÄsに üらüs@"

LeftoversDescription:
	db   "そtびするö 1P-lごöに  "
	next "Äsり<MN>yが30 wsふyする@"

IceWingDescription:
	db   "そtびするö "
	next "öyし<PK>ぼtぎ<MN>が 10rがる@"

ThunderWingDescription:
	db   "そtびするö "
	next "すばsさが 10rがる@"

FireWingDescription:
	db   "そtびするö "
	next "öyし<PK>こtげxが 10rがる@"

Item96Description:
	db   "?"
	next "?@"

DragonScaleDescription:
	db   "そtびするö ドfゴlPBプの "
	next "わざのsり<MN>yを vわmられる@"

BerserkGeneDescription:
	db   "そtびするö "
	next "すべäの のtり<MN>yが 10rがる@"

HeartStoneDescription:
	db   "öyäsの ポIblを しんwさせる@"

FireTailDescription:
	db   "そtびするö "
	next "こvり じ<MN>tÄsに üらüs@"

ThunderTailDescription:
	db   "そtびするö "
	next ";( じ<MN>tÄsに üらüs@"

SacredAshDescription:
	db   "すべäのポIblを Äsり<MN>y1で"
	next "ひんし じ<MN>tÄswら wsふyする@"

TMHolderDescription:
	db   "わざ;Llを しまt :gダ@"

MailDescription:
	db   "öyし<PK> ABS]@"

BallHolderDescription:
	db   "öyし<PK> ABS]@"

BagDescription:
	db   "ふÜtの どtぐを しまt :gダ@"

ImportantBagDescription:
	db   "だsじü どtぐを しまt :gダ@"

PoisonStoneDescription:
	db   "öyäsの ポIblを しんwさせる@"

ItemA3Description:
	db   "?"
	next "?@"

ItemA4Description:
	db   "?"
	next "?@"

ItemA5Description:
	db   "?"
	next "?@"

ItemA6Description:
	db   "?"
	next "?@"

ItemA7Description:
	db   "?"
	next "?@"

ItemA8Description:
	db   "?"
	next "?@"

ItemA9Description:
	db   "?"
	next "?@"

ItemAADescription:
	db   "?"
	next "?@"

ItemABDescription:
	db   "?"
	next "?@"

ItemACDescription:
	db   "?"
	next "?@"

ItemADDescription:
	db   "?"
	next "?@"

ItemAEDescription:
	db   "?"
	next "?@"

ItemAFDescription:
	db   "?"
	next "?@"

ItemB0Description:
	db   "?"
	next "?@"

ItemB1Description:
	db   "?"
	next "?@"

ItemB2Description:
	db   "?"
	next "?@"

ItemB3Description:
	db   "?"
	next "?@"

ItemB4Description:
	db   "?"
	next "?@"

ItemB5Description:
	db   "?"
	next "?@"

ItemB6Description:
	db   "?"
	next "?@"

ItemB7Description:
	db   "?"
	next "?@"

ItemB8Description:
	db   "?"
	next "?@"

ItemB9Description:
	db   "?"
	next "?@"

ItemBADescription:
	db   "?"
	next "?@"

ItemBBDescription:
	db   "?"
	next "?@"

ItemBCDescription:
	db   "?"
	next "?@"

ItemBDDescription:
	db   "?"
	next "?@"

ItemBEDescription:
	db   "?"
	next "?@"

ItemBFDescription:
	db   "?"
	next "?@"

ItemC0Description:
	db   "?"
	next "?@"

ItemC1Description:
	db   "?"
	next "?@"

ItemC2Description:
	db   "?"
	next "?@"

ItemC3Description:
	db   "?"
	next "?@"

TM01Description:
	db   "わざ;Ll01@"

TM02Description:
	db   "わざ;Ll02@"

TM03Description:
	db   "わざ;Ll03@"

TM04Description:
	db   "わざ;Ll04@"

ItemC8Description:
	db   "?"
	next "?@"

TM05Description:
	db   "わざ;Ll05@"

TM06Description:
	db   "わざ;Ll06@"

TM07Description:
	db   "わざ;Ll07@"

TM08Description:
	db   "わざ;Ll08@"

TM09Description:
	db   "わざ;Ll09@"

TM10Description:
	db   "わざ;Ll10@"

TM11Description:
	db   "わざ;Ll11@"

TM12Description:
	db   "わざ;Ll12@"

TM13Description:
	db   "わざ;Ll13@"

TM14Description:
	db   "わざ;Ll14@"

TM15Description:
	db   "わざ;Ll15@"

TM16Description:
	db   "わざ;Ll16@"

TM17Description:
	db   "わざ;Ll17@"

TM18Description:
	db   "わざ;Ll18@"

TM19Description:
	db   "わざ;Ll19@"

TM20Description:
	db   "わざ;Ll20@"

TM21Description:
	db   "わざ;Ll21@"

TM22Description:
	db   "わざ;Ll22@"

TM23Description:
	db   "わざ;Ll23@"

TM24Description:
	db   "わざ;Ll24@"

TM25Description:
	db   "わざ;Ll25@"

TM26Description:
	db   "わざ;Ll26@"

TM27Description:
	db   "わざ;Ll27@"

TM28Description:
	db   "わざ;Ll28@"

ItemE1Description:
	db   "?"
	next "?@"

TM29Description:
	db   "わざ;Ll29@"

TM30Description:
	db   "わざ;Ll30@"

TM31Description:
	db   "わざ;Ll31@"

TM32Description:
	db   "わざ;Ll32@"

TM33Description:
	db   "わざ;Ll33@"

TM34Description:
	db   "わざ;Ll34@"

TM35Description:
	db   "わざ;Ll35@"

TM36Description:
	db   "わざ;Ll36@"

TM37Description:
	db   "わざ;Ll37@"

TM38Description:
	db   "わざ;Ll38@"

TM39Description:
	db   "わざ;Ll39@"

TM40Description:
	db   "わざ;Ll40@"

TM41Description:
	db   "わざ;Ll41@"

TM42Description:
	db   "わざ;Ll42@"

TM43Description:
	db   "わざ;Ll43@"

TM44Description:
	db   "わざ;Ll44@"

TM45Description:
	db   "わざ;Ll45@"

TM46Description:
	db   "わざ;Ll46@"

TM47Description:
	db   "わざ;Ll47@"

TM48Description:
	db   "わざ;Ll48@"

TM49Description:
	db   "わざ;Ll49@"

TM50Description:
	db   "わざ;Ll50@"

HM01Description:
	db   "ひでん;Ll01@"

HM02Description:
	db   "ひでん;Ll02@"

HM03Description:
	db   "ひでん;Ll03@"

HM04Description:
	db   "ひでん;Ll04@"

HM05Description:
	db   "ひでん;Ll05@"

HM06Description:
	db   "ひでん;Ll06@"

HM07Description:
	db   "ひでん;Ll07@"

ItemFFDescription:
	db   "?"
	next "?@"
